name: bump-version-then-release

on:
  workflow_run:
    workflows: [check-build-test]
    types: [completed]

jobs:
  bump-version-then-release:
    runs-on: ubuntu-latest
    steps:
      - name: Print the github.event contexts
        env: 
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_EVENT"
        
      - name: Checkout Code
        uses: actions/checkout@v2
          
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-on-empty: 'false'

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
